apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx2-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      version: v2.0 
  replicas: 2
  template:  
    metadata:
      labels:
        app: nginx
        version: v2.0 
    spec:
      containers:
      - name: nginx2
        image: mikiha/nginx-server:2.0
        ports:
        - containerPort: 80
